<?php
/**
 * 全局函数和常量
 */
define("CODE_UNPACK_REQUEST_FAILED", 500);
define("ERR_ACTION_CLASS_NOT_EXISTS", 501);
define("CODE_ACTION_METHOD_NOT_EXISTS", 502);



define("CODE_OUTPUT_HTML", 200);
define("CODE_OUTPUT_JSON", 201);
